///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebWordPressLibrary.TesterB
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TesterB element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e8812a4e-0911-4a0d-8ab1-1d5092158d75")]
    public partial class TesterB : RepoGenBaseFolder
    {
        static TesterB instance = new TesterB();

        /// <summary>
        /// Gets the singleton class instance representing the TesterB element repository.
        /// </summary>
        [RepositoryFolder("e8812a4e-0911-4a0d-8ab1-1d5092158d75")]
        public static TesterB Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TesterB() 
            : base("TesterB", "/", null, 0, false, "e8812a4e-0911-4a0d-8ab1-1d5092158d75", ".\\RepositoryImages\\TesterBe8812a4e.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e8812a4e-0911-4a0d-8ab1-1d5092158d75")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TesterBFolders
    {
    }
#pragma warning restore 0436
}
