///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebWordPressLibrary.TesterA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TesterA element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f31e89c1-60fb-4184-906b-b2902dc8f60e")]
    public partial class TesterA : RepoGenBaseFolder
    {
        static TesterA instance = new TesterA();
        TesterAFolders.WordPress_DemoAppFolder _wordpress_demo;

        /// <summary>
        /// Gets the singleton class instance representing the TesterA element repository.
        /// </summary>
        [RepositoryFolder("f31e89c1-60fb-4184-906b-b2902dc8f60e")]
        public static TesterA Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TesterA() 
            : base("TesterA", "/", null, 0, false, "f31e89c1-60fb-4184-906b-b2902dc8f60e", ".\\RepositoryImages\\TesterAf31e89c1.rximgres")
        {
            _wordpress_demo = new TesterAFolders.WordPress_DemoAppFolder(this);
        }

#region Variables

        string _varPostURL = "http://webtest.ranorex.org/";

        /// <summary>
        /// Gets or sets the value of variable varPostURL.
        /// </summary>
        [TestVariable("342c4b3f-d50c-4ee2-a1e3-c123ce7d1e10")]
        public string varPostURL
        {
            get { return _varPostURL; }
            set { _varPostURL = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f31e89c1-60fb-4184-906b-b2902dc8f60e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WordPress_Demo folder.
        /// </summary>
        [RepositoryFolder("b9c93ca3-701e-4439-bcb5-49663ec123e0")]
        public virtual TesterAFolders.WordPress_DemoAppFolder WordPress_Demo
        {
            get { return _wordpress_demo; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TesterAFolders
    {
        /// <summary>
        /// The WordPress_DemoAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9c93ca3-701e-4439-bcb5-49663ec123e0")]
        public partial class WordPress_DemoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _recentpostInfo;
            RepoItemInfo _dashboardInfo;

            /// <summary>
            /// Creates a new WordPress_Demo  folder.
            /// </summary>
            public WordPress_DemoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WordPress_Demo", "/dom[@domain='webtest.ranorex.org']", parentFolder, 30000, null, false, "b9c93ca3-701e-4439-bcb5-49663ec123e0", "")
            {
                _recentpostInfo = new RepoItemInfo(this, "RecentPost", ".//li[#'recent-posts-2']//a[@href=$varPostURL]", 30000, null, "4a632421-1c26-4572-85b0-2e52270f3928");
                _dashboardInfo = new RepoItemInfo(this, "Dashboard", ".//li[#'menu-dashboard']", 30000, null, "c4a1f763-d69f-4c41-a31a-e481faf9bd6a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9c93ca3-701e-4439-bcb5-49663ec123e0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9c93ca3-701e-4439-bcb5-49663ec123e0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RecentPost item.
            /// </summary>
            [RepositoryItem("4a632421-1c26-4572-85b0-2e52270f3928")]
            public virtual Ranorex.ATag RecentPost
            {
                get
                {
                    return _recentpostInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RecentPost item info.
            /// </summary>
            [RepositoryItemInfo("4a632421-1c26-4572-85b0-2e52270f3928")]
            public virtual RepoItemInfo RecentPostInfo
            {
                get
                {
                    return _recentpostInfo;
                }
            }

            /// <summary>
            /// The Dashboard item.
            /// </summary>
            [RepositoryItem("c4a1f763-d69f-4c41-a31a-e481faf9bd6a")]
            public virtual Ranorex.LiTag Dashboard
            {
                get
                {
                    return _dashboardInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Dashboard item info.
            /// </summary>
            [RepositoryItemInfo("c4a1f763-d69f-4c41-a31a-e481faf9bd6a")]
            public virtual RepoItemInfo DashboardInfo
            {
                get
                {
                    return _dashboardInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
